ci:
  skip: [fmt]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          [
            argon2-cffi,
            asyncpg,
            "camel-converter[pydantic]",
            faker,
            fastapi,
            meilisearch-python-sdk,
            passlib,
            pydantic,
            pydantic-settings,
            pyjwt,
            python-dotenv,
            rich,
            srsly,
            typer,
            "uvicorn[standard]",
          ]
        exclude: ".*/test_.*\\.py|.*/conftest\\.py|pieces/rest_api_postgres/python/.*"
        args: [--explicit-package-bases] # This is because of the mono repo type setup
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        pass_filenames: false
        files: ^pieces/rest_api_postgres/python/
        additional_dependencies:
          [
            asyncpg,
            "camel-converter[pydantic]",
            fastapi,
            pydantic,
            pydantic-settings,
            "uvicorn[standard]",
          ]
        entry: bash -c 'cd pieces/rest_api_postgres/python && mypy -p app "$@"' --
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
