[workspace]

members = [
    "rust/hello_world",
    "rust/regex_json",
    "rust/datetime_parsing_csv",
    "rust/mock_data",
    "rust/postgres_etl",
    "rust/intro",
    "rust/age_groups_csv",
]
resolver = "1"
