[workspace]

members = [
  "pieces/hello_world/rust",
  "pieces/age_groups_csv/rust",
  # "rust/hello_world",
  #  "rust/regex_json",
  #  "rust/datetime_parsing_csv",
  #  "rust/mock_data",
  #  "rust/postgres_etl",
  #  "rust/intro",
  #  "rust/age_groups_csv",
]
resolver = "2"
