[workspace]

members = [
  "pieces/age_groups_csv/rust",
  "pieces/datetime_parsing_csv/rust",
  "pieces/hello_world/rust",
  "pieces/intro/rust",
  "pieces/mock_data/rust",
  "pieces/postgres_etl/rust",
  "pieces/regex_json/rust",
]
resolver = "2"
