[book]
authors = ["prrao87", "sanders41"]
language = "en"
multilingual = false
src = "src"
title = "Rust in Pieces"

[output.html]
site-url = "/book/"
additional-css = ["theme/extra.css"]

# [output.html.fold]
# enable = true
# level = 2
