name: Deploy mdBook to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

env:
  CUSTOM_DOMAIN: rustinpieces.dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest

      - run: |
          touch book/.nojekyll
          cd book
          mdbook test
          mdbook build

      - name: Create CNAME file
        run: |
          echo "$CUSTOM_DOMAIN" > ./book/CNAME
          echo "Created CNAME in ./book/CNAME: $CUSTOM_DOMAIN"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./book/book"
